name:   Release Suite lcli

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    DOCKER_PASSWORD: ${{ secrets.DH_KEY }}
    DOCKER_USERNAME: ${{ secrets.DH_ORG }}
    REPO_NAME: ${{ github.repository_owner }}/lighthouse
    IMAGE_NAME: ${{ github.repository_owner }}/lighthouse
    # Enable self-hosted runners for the sigp repo only.
    SELF_HOSTED_RUNNERS: ${{ github.repository == 'sigp/lighthouse' }}

jobs:
    extract-version:
        runs-on: ubuntu-latest
        steps:
            - name: Extract version
              run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT
              id: extract_version
        outputs:
            VERSION: ${{ steps.extract_version.outputs.VERSION }}
    build:
        name:   Build Release
        strategy:
            matrix:
                arch: [aarch64-unknown-linux-gnu,
                       x86_64-unknown-linux-gnu,
                       x86_64-apple-darwin,
                       x86_64-windows]
                include:
                    -   arch: aarch64-unknown-linux-gnu
                        runner: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "release", "large"]') || 'ubuntu-latest'  }}
                        profile: maxperf
                    -   arch: x86_64-unknown-linux-gnu
                        runner: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "release", "large"]') || 'ubuntu-latest'  }}
                        profile: maxperf
                    -   arch: x86_64-apple-darwin
                        runner: macos-13
                        profile: maxperf
                    -   arch: x86_64-windows
                        runner: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "windows", "release"]') || 'windows-2019'  }}
                        profile: maxperf

        runs-on:    ${{ matrix.runner }}
        needs: extract-version
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Get latest version of stable Rust
              if: env.SELF_HOSTED_RUNNERS == 'false'
              run: rustup update stable

            # ==============================
            # Windows dependencies
            # ==============================

            - uses: KyleMayes/install-llvm-action@v1
              if: env.SELF_HOSTED_RUNNERS == 'false' && startsWith(matrix.arch, 'x86_64-windows')
              with:
                version: "17.0"
                directory: ${{ runner.temp }}/llvm
            - name: Set LIBCLANG_PATH
              if: startsWith(matrix.arch, 'x86_64-windows')
              run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV

            # ==============================
            #       Builds
            # ==============================

            - name: Build Lighthouse for aarch64-unknown-linux-gnu
              if:   matrix.arch == 'aarch64-unknown-linux-gnu'
              run:  |
                cargo install cross
                env CROSS_PROFILE=${{ matrix.profile }} make build-aarch64
                env CROSS_PROFILE=${{ matrix.profile }} make build-lcli-aarch64

            - name: Build Lighthouse for x86_64-unknown-linux-gnu
              if:   matrix.arch == 'x86_64-unknown-linux-gnu'
              run:  |
                cargo install cross
                env CROSS_PROFILE=${{ matrix.profile }} make build-x86_64
                env CROSS_PROFILE=${{ matrix.profile }} make build-lcli-x86_64

            - name: Move cross-compiled binary
              if:  contains(matrix.arch, 'unknown-linux-gnu')
              run: mv target/${{ matrix.arch }}/${{ matrix.profile }}/lighthouse ~/.cargo/bin/lighthouse

            - name: Build Lighthouse for x86_64-apple-darwin
              if:   matrix.arch == 'x86_64-apple-darwin'
              run:  cargo install --path lighthouse --force --locked --features portable,gnosis --profile ${{ matrix.profile }}

            - name: Build Lighthouse for Windows
              if:   matrix.arch == 'x86_64-windows'
              run:  cargo install --path lighthouse --force --locked --features portable,gnosis --profile ${{ matrix.profile }}

            - name: Compress artifacts
              if: startsWith(matrix.arch, 'x86_64-windows') != true
              run: |
                  mkdir artifacts
                  mv ~/.cargo/bin/lighthouse ./artifacts
                  mv ~/.cargo/bin/lcli ./artifacts
                  cd artifacts
                  tar -czf lighthouse-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.arch }}.tar.gz lighthouse
                  mv *tar.gz* ..

            - name: Compress artifacts Windows
              if: startsWith(matrix.arch, 'x86_64-windows')
              run: |
                  mkdir artifacts
                  move $env:USERPROFILE/.cargo/bin/lighthouse.exe ./artifacts
                  move $env:USERPROFILE/.cargo/bin/lcli.exe ./artifacts
                  cd artifacts
                  tar -czf lighthouse-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.arch }}.tar.gz lighthouse.exe
                  move *tar.gz* ..

            # Create release
            - name: Generate release tag
              id: tag
              run: |
                sudo timedatectl set-timezone Asia/Ho_Chi_Minh
                sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
                echo "release_tag=ActionBuild_${{ matrix.arch }}_$(date +"%Y.%m.%d_%H-%M-%S")" >> $GITHUB_OUTPUT
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ steps.tag.outputs.release_tag }}
                files: |
                  ./lighthouse-${{ needs.extract-version.outputs.VERSION }}-${{ matrix.arch }}.tar.gz
            # Done release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
