name:   Release Suite lcli

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    REPO_NAME: ${{ github.repository_owner }}/lighthouse
    IMAGE_NAME: ${{ github.repository_owner }}/lighthouse
    # Enable self-hosted runners for the sigp repo only.
    SELF_HOSTED_RUNNERS: ${{ github.repository == 'sigp/lighthouse' }}

jobs:
    extract-version:
        runs-on: ubuntu-latest
        steps:
            - name: Extract version
              run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT
              id: extract_version
        outputs:
            VERSION: ${{ steps.extract_version.outputs.VERSION }}
    build:
        name:   Build Release
        strategy:
            matrix:
                arch: [x86_64-unknown-linux-gnu]
                include:
                    -   arch: x86_64-unknown-linux-gnu
                        runner: ${{ github.repository == 'sigp/lighthouse' && fromJson('["self-hosted", "linux", "release", "large"]') || 'ubuntu-latest'  }}
                        profile: maxperf

        runs-on:    ${{ matrix.runner }}
        needs: extract-version
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Get latest version of stable Rust
              if: env.SELF_HOSTED_RUNNERS == 'false'
              run: rustup update stable

            - name: Build Lighthouse for x86_64-unknown-linux-gnu
              if:   matrix.arch == 'x86_64-unknown-linux-gnu'
              run:  |
                cargo install cross
                cross build --bin lcli --target x86_64-unknown-linux-gnu --features "portable,spec-minimal" --profile "${{ matrix.profile }}" --locked
            # Create release
            - name: Generate release tag
              id: tag
              run: |
                sudo timedatectl set-timezone Asia/Ho_Chi_Minh
                sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
                echo "release_tag=ActionBuild_${{ matrix.arch }}_$(date +"%Y.%m.%d_%H-%M-%S")" >> $GITHUB_OUTPUT
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: ${{ steps.tag.outputs.release_tag }}
                files: |
                  /home/runner/work/lighthouse/lighthouse/target/x86_64-unknown-linux-gnu/maxperf/lcli
            # Done release

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
